apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: projetocompass
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/pv-mysql
