apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: projetocompass
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /data/pv-mysql/
