apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: projetocompass
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql-svc
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostpath-privileged
          mountPath: /var/www/html
      securityContext: {}
      volumes:
        - name: hostpath-privileged
          hostPath:
            # directory location on host
            path: /data/pv-wordpress/
            # this field is optional
            type: DirectoryOrCreate