apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: projetocompass
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pv-wordpress/